### ISSUE TITLE
removeWithBackspace not working

### ISSUE THREAD

**Issue by asaklex** [dangribbin/jQuery-Tag-This#17]
removeWithBackspace is not working. Either removeWithBackspace is set to true or false in the options, the plugin deletes item with backspace.

Another issue is that if you delete the last letter of a tag, the previous tag is deleted.

**Comment by subliminality** [comment]
The fix for removeWithBackspace not working is very is easy. Line 125 simply change from:

`else if ( e.keyCode === 8 && $(this).val() === '' ) {`
to
`else if ( settings.removeWithBackspace && e.keyCode === 8 && $(this).val() === '' ) {`
